const websites = [
    {
        id: 1,
        category: "websites",
        title: "Web Fundamentals",
        description: "After my first experience with web development in a web fundamentals course, I built a practice portfolio website to showcase my academic journey. The site features three distinct pages: the first describing html and css principles, one highlighting the courses I had completed, and another showcasing my projects. Throughout the process, I applied fundamental web design principles that I had learned.",
        software:["HTML, CSS"],
        date: "July 2024",
        link: "https://amhart02.github.io/wdd130/portfolio/index.html",
        image: "/images/websites/webFundamentals.png"
    },
    {
        id: 2,
        category: "websites",
        title: "My Favorite Movies",
        description: "In my second web development class, I designed a two-page website featuring my favorite movies and a movie trivia game. The first page includes a list of my favorite films, each accompanied by a title, description, and image. The page also allows users to search and sort the movies dynamically. The second page offers a trivia game where users can test their knowledge by answering questions related to the featured films",
        software:["HTML, CSS, JavaScript"],
        date: "July 2024",
        link: "https://amhart02.github.io/wdd131/movies/index.html",
        image: "/images/websites/myFavoriteMovies.png"
    },
    {
        id: 3,
        category: "websites",
        title: "Fur Facts",
        description: "A fun and educational website featuring information about specific cat and dog breeds. Users can explore various breeds, search for their favorites, and take a quiz to identify breeds by picture. This was my first experience creating a website utilizing an API.",
        software:["HTML, CSS, JavaScript, API"],
        date: "December 2024",
        link: "https://fur-facts.netlify.app/",
        image: "/images/websites/furFacts.png"
    },
    {
        id: 4,
        category: "websites",
        title: "Date Map",
        description: "After becoming proficient at beginning web development principles I created a website featuring a map from Google Maps API that allows custom markers. Each marker indicates a location in Rexburg, Idaho for a date idea. Different colors are used to differenciate between free and paid dates.",
        software:["HTML, CSS, JavaScript, Google Maps API"],
        date: "December 2024",
        link: "https://date-map.netlify.app/",
        image: "/images/websites/dateMap.png"
    },  
    {
        id: 5,
        category: "websites",
        title: "Michael Shoaf Music Portfolio",
        description: "Along with several other students in the Web Design and Development society, I designed and developed a music portfolio for an adjunct music professor at BYU-Idaho. The site features pictures and videos from important performances, a biography of his career, a contact form, and links to press kits for his roles as director and performer.",
        software:["HTML, CSS, JavaScript"],
        date: "April 2025",
        link: "https://www.michaelshoafcountertenor.com/index.html",
        image: "/images/websites/musicPortfolio.png"
    },
    {
        id: 6,
        category: "websites",
        title: "Game Scape",
        description: "An interactive website for gamers to explore and discover new games. Users can search games by name or browse by genre. Games can be \"liked\" and displayed on a secondary page. Games are generated by an API and liked games are saved using local storage.",
        software:["HTML, CSS, JavaScript, API"],
        date: "July 2025",
        link: "https://gamescapeproject.netlify.app/",
        image: "/images/websites/gameScape.png"
    },
    {
        id: 7,
        category: "websites",
        title: "Space Wars Style Stage",
        description: "After studying SCSS, two fellow classmates and I created a Style Stage website with a \"Space Wars\" theme. Style Stage is a showcase project where developers can redesign a specific website template using only CSS. We primarily used SCSS to change the layout, colors, and add lightsabers to the website.",
        software:["HTML, SASS"],
        date: "July 2025",
        link: "https://spacewarsstylestage.netlify.app/",
        image: "/images/websites/spaceWars.png"
    },
    {
        id: 7,
        category: "websites",
        title: "Car Dealership",
        description: "My previously learned front-end principles with newly found back-end skills were combined to create this project. It is a mock car dealership website that allows users to browse available cars, contact management, write reviews, and send in repair requests. Employees and managers can also log in to manage requests, reviews, messages from users, and cars.",
        software:["EJS, SASS, Node.js, Express.js"],
        date: "July 2025",
        link: "https://cse340final.onrender.com/",
        image: "/images/websites/carDealership.png"
    },
]

export default websites;